name: Build manually
on: [workflow_dispatch]

env:
  POSTGRES_VERSION: "14.2"
  RELEASE_VERSION: "14.2-gis"
  # See https://docs.aws.amazon.com/AmazonRDS/latest/PostgreSQLReleaseNotes/postgresql-extensions.html#postgresql-extensions-14x
  POSTGIS_VERSION: "2.5.9" # TODO 3.1.5

jobs:
  tasks: # TODO Remove
    name: List tasks on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 15
      - name: List tasks
        run: ./gradlew tasks
      - name: List tasks -PpostgisVersion=$POSTGIS_VERSION
        run: ./gradlew tasks -PpostgisVersion=$POSTGIS_VERSION
      - name: List all tasks
        run: ./gradlew tasks --all
      - name: List :repacked-platforms tasks
        run: ./gradlew :repacked-platforms:tasks --all
      - name: List :debian-platforms tasks
        run: ./gradlew :debian-platforms:tasks --all
      - name: Query all tasks
        run: ./gradlew -q :tasks --all
  tasks-win: # TODO Remove
    name: List tasks on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 15
      - name: List tasks
        run: ./gradlew tasks
      - name: List all tasks
        run: ./gradlew tasks --all
      - name: List :repacked-platforms tasks
        run: ./gradlew :repacked-platforms:tasks --all
      - name: List :debian-platforms tasks
        run: ./gradlew :debian-platforms:tasks --all
      - name: Query all tasks
        run: ./gradlew -q :tasks --all
  linux:
    name: PostgreSQL (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 15
      - name: List :debian-platforms tasks # TODO Remove
        run: ./gradlew :debian-platforms:tasks --all
      - name: List :custom-debian-platforms tasks # TODO Remove
        run: ./gradlew :custom-debian-platforms:tasks --all
      - name: Build Bundle
        run: ./gradlew :custom-debian-platforms:buildCustomDebianBundle -Pversion=$RELEASE_VERSION -PpgVersion=$POSTGRES_VERSION -PpostgisVersion=$POSTGIS_VERSION
      - name: Test PostgreSQL bundle
        run: ./gradlew :custom-debian-platform:testCustomDebianJar -Pversion=$POSTGRES_VERSION-TEST -PpgVersion=$POSTGRES_VERSION -PpostgisVersion=$POSTGIS_VERSION
        timeout-minutes: 10
  macos:
    name: PostgreSQL (MacOS)
    runs-on: macos-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 15
      - name: Test PostgreSQL bundle
        run: ./gradlew :repacked-platforms:testAmd64DarwinJar -Pversion=$POSTGRES_VERSION-TEST -PpgVersion=$POSTGRES_VERSION # TODO -PpostgisVersion=$POSTGIS_VERSION
        timeout-minutes: 10
  windows:
    name: PostgreSQL (Windows)
    runs-on: windows-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 15
      - name: Install GNU Wget
        run: choco install wget
      - name: Update system paths
        run: echo $PGBIN >> $GITHUB_PATH
        shell: bash
      - name: List :repacked-platforms tasks # TODO Remove
        run: ./gradlew :repacked-platforms:tasks --all
      - name: Test PostgreSQL bundle
        run: ./gradlew :repacked-platforms:testAmd64WindowsJar -Pversion=$POSTGRES_VERSION-TEST -PpgVersion=$POSTGRES_VERSION # TODO -PpostgisVersion=$POSTGIS_VERSION
        shell: bash
        timeout-minutes: 10
